### ISSUE TITLE
icon/logo missing

### ISSUE THREAD

**Issue by ghost** [nick-gravgaard/windowlab#1]
windowlab needs an icon/logo for using as lightdm badge ( like /usr/share/unity-greeter/custom_*_badge.png ) - what can be used there?

**Comment by nick-gravgaard** [comment]
Hi, and sorry to take so long to reply. I'm not sure this repo is the right place to store icons for each display manager. For unity-greeter I think the ["unity-greeter-badges" package](https://launchpad.net/unity-greeter-badges) is where it should be.
